settings:
  prefix: "&6&l[zGangs]&r"

gangs:
  max-name-length: 15
  min-name-length: 3
  banned-names:
    - "fuck"
  name-regex: "([A-Za-z0-9æøåÆØÅ])+"
  gang-transfer-cost: 50000
  gang-create-cost: 5000
